name: Run Unit Tests with Code Coverage on PRs

# Controls when the action will run.
on:
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
      - name: Test with pytest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          DEFAULT_LIMIT: 1
        run: |
          poetry run pytest --cov --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: |
            htmlcov
          retention-days: 20
